uni_fit/urls.py
from django.urls import path
from uni_fit import views

app_name = 'uni_fit'

urlpatterns = [
    path('', views.index, name='index'),
    path('home/',views.home, name='home'),
    path('profile/',views.profile, name='profile'),
    path('university/<int:id>',views.university, name='university'),
    path('fav/<int:id>',views.favourite_add, name='favourite_add'),
    path('favourites/',views.favourite_list, name='favourite_list'),
]

unifit/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from uni_fit import views

urlpatterns = [
    path('',views.index, name='index'),
    path('uni_fit/', include('uni_fit.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('registration.backends.simple.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

uni_fit/models.py
from django.db import models
from django.contrib.auth.models import User
from django.forms import CharField

class UserProfile(models.Model):
    # This line is required. Links UserProfile to a User model instance.
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    # The additional attributes we wish to include.
    website = models.URLField(blank=True)
    picture = models.ImageField(upload_to='profile_images', blank=True)

    def __str__(self):
        return self.user.username


class Users(models.Model):
    UserId = models.IntegerField
    Firstname = models.CharField(max_length=30)
    Lastname = models.CharField(max_length=30)
    Email = models.CharField(max_length=100)
    Password = models.CharField(max_length=100)
    Country = models.CharField(max_length=100)
    DepartmentPreference = models.CharField(max_length=100)
    SubjectPreference = models.CharField(max_length=100)
    Grade = models.IntegerField
    

    class Meta:
        verbose_name_plural = "Users"

    def __str__(self):
        return self.UserId

class University(models.Model):
    UniId = models.AutoField(primary_key=True, auto_created=True)
    UniName = models.CharField(max_length=100, unique=True, default='TestName')
    Country = models.CharField(max_length=100)
    UniRank = models.IntegerField(default=0)
    About = models.CharField(max_length=500)
    Link = models.CharField(max_length=30)
    FavouriteUnversity = models.ManyToManyField(User,related_name='favourite',default=None, blank=True)

    class Meta:
        verbose_name_plural = "Universities"

    def __str__(self):
        return self.UniName

class University_Department(models.Model):
    DeptId = models.AutoField(primary_key=True, auto_created=True)
    UniName = models.ForeignKey(University, on_delete=models.CASCADE, default=0)
    DeptName = models.CharField(max_length=100)
    DeptRank = models.IntegerField(default=0)
    Link = models.CharField(max_length=500)

    class Meta:
        verbose_name_plural = "University_Departments"    

    def __str__(self):
        return self.DeptName    

class Review(models.Model):
    UniId = models.IntegerField
    Title = models.CharField(max_length=300)
    Comment = models.CharField(max_length=300)
    StudentSatisfaction = models.IntegerField
    EntryStandards = models.IntegerField
    GraduateProspect = models.IntegerField  

    class Meta:
        verbose_name_plural = "Reviews"     

    def __str__(self):
        return self.UniId


class Reddit(models.Model):
    UniName  = models.ForeignKey(University, on_delete=models.CASCADE)
    SubReddit = models.CharField(max_length=100)
    Link = models.CharField(max_length=500) 

    class Meta:
        verbose_name_plural = "Reddits"     

    def __str__(self):
        return self.UniName 

# this is just an extra model i used to create comments for, the comment model refers to this
# but for the final code we would need to use the University model rather than
# the Post model
class Post(models.Model):
    title = models.CharField(max_length=200, unique=True)

    def __str__(self):
        return self.title

class Comment(models.Model):
    uni = models.ForeignKey(Post,on_delete=models.CASCADE,related_name='comments')
    title = models.CharField(max_length=80)
    comment = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ['created_on']

    def __str__(self):
        return 'Comment {} by {}'.format(self.comment, self.title)

uni_fit/forms.py
from dataclasses import field
from django import forms
from uni_fit.models import UserProfile, Comment
from django.contrib.auth.models import User


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username','email','password',)

class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('website','picture',)

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('title', 'comment')

uni_fit/views.py
from webbrowser import get
from django.urls import reverse
from django.shortcuts import get_list_or_404, get_object_or_404, render, redirect
from django.http import HttpResponse, HttpResponseRedirect
from uni_fit.forms import UserForm, UserProfileForm, CommentForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
import profile
from stat import FILE_ATTRIBUTE_SPARSE_FILE
from uni_fit.reddit import get_posts
from uni_fit.models import University, Users, Post, University_Department


def index(request):
    return render(request, 'uni_fit/index.html',)

@login_required
def home(request):
    universities = University.objects.all().order_by('UniRank')
    countrylist=University.objects.all().values_list('Country', flat=True).distinct()
    departmentlist=University_Department.objects.all().values_list('DeptName', flat=True).distinct()    
    if 'countrydropdown' in request.GET or 'departmentdropdown' in request.GET:
        countrydropdown = request.GET.get('countrydropdown')
        departmentdropdown = request.GET.get('departmentdropdown')
        UniNameList=University_Department.objects.filter(DeptName=departmentdropdown).values_list('UniName', flat=True)
        if countrydropdown!='all' and countrydropdown is not None:
            universities = universities.filter(Country=countrydropdown)
        if departmentdropdown!='all' and departmentdropdown is not None:
            universities = universities.filter(UniId__in=UniNameList)
    return render(request, 'uni_fit/home.html', {'universities': universities, 'countrylist':countrylist, 'departmentlist':departmentlist} )

def profile(request):
    universities = University.objects.all().order_by('UniRank')[:15]        
    if 'grade' in request.GET:
        grade = request.GET.get('grade')
        if int(grade) < 90 and int(grade) >= 80:
            universities = University.objects.all().order_by('UniRank')[5:20]
        if int(grade) < 80:
            universities = University.objects.all().order_by('UniRank')[10:]
        
    return render(request, 'uni_fit/profile.html', {'universities': universities})

@login_required
def favourite_add(request, id):
    university = get_object_or_404(University, UniId=id)
    if (university.FavouriteUnversity.filter(id=request.user.id).exists()):
        university.FavouriteUnversity.remove(request.user)
    else:
        university.FavouriteUnversity.add(request.user)
    return HttpResponseRedirect(request.META['HTTP_REFERER'])

@login_required
def favourite_list(request):
    fav_list = University.objects.filter(FavouriteUnversity=request.user.id)
    return render(request, 'uni_fit/favourites.html', {'fav_list': fav_list})

def university(request, id):
    result_list = []
    result_list = get_posts()
    #return render(request, 'uni_fit/university.html', {'result_list': result_list})

    #university data for the page
    unidata = University.objects.get(UniId=id)

#def post_detail(request):
    template_name = 'uni_fit/university.html'
    uni = get_object_or_404(Post)
    comments = uni.comments.filter(active=True)
    new_comment = None
    # Comment posted
    if request.method == 'POST':
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():

            # Create Comment object but don't save to database yet
            new_comment = comment_form.save(commit=False)
            # Assign the current post to the comment
            new_comment.uni = uni
            # Save the comment to the database
            new_comment.save()
            comment_form = CommentForm()
    else:
        comment_form = CommentForm()
    
    return render(request, template_name, {'uni': uni,
                                           'comments': comments,
                                           'new_comment': new_comment,
                                           'comment_form': comment_form,
                                           'result_list': result_list,
                                           'unidata': unidata})

templates/uni_fit/base.html
<!DOCTYPE html>
{% load staticfiles %}

<html>
    <head lang="en">
        <meta charset="UTF-8"/>
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>
            UniFit -
            {% block title_block %}
                Guide
            {% endblock %}
        </title>

        <!-- CSS -->
        <link rel="stylesheet" href="{% static 'css/base.css' %}">
        <!-- BOOTSTRAP CSS -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
        <link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css" rel="stylesheet">
        <!--FAVICON-->
        <link rel="shortcut icon" type="image/png" href="/static/images/favicon.png">
        <!--FONT AWESOME ICONS-->
        <script src="https://kit.fontawesome.com/3691efe897.js" crossorigin="anonymous"></script>
    </head>

    <body>
        <div>
        <nav class="navbar navbar-expand-sm bg-light">
            <ul>
                {% if user.is_authenticated %}
                <!-- Show these links when the user is logged in -->
                <li style = "align-items: left;" >
                    <a id="show" href="{% url 'uni_fit:home' %}"><img src="/static/images/logo.png"></a>
                </li>
                {% endif %}
                </ul>
                
                <ul class="navbar-nav ms-auto">
                    {% if user.is_authenticated %}
                <li class="nav-item">
                  <a class="nav-link" id="hello-user" href="{% url 'uni_fit:profile' %}">Hello, {{user.username}}!</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" id="favs" href="{% url 'uni_fit:favourite_list' %}">My Favourites</a>
                </li>

                <li class="nav-item">
                  <a class="nav-link active" id="logout" href="{% url 'auth_logout' %}?next={% url 'uni_fit:index' %}">Logout</a>
                </li>
       

                {% else %}
                <!-- Show these links when the user is logged out -->
                <li>
                    <a id="show" href="{% url 'uni_fit:index' %}"><img src="/static/images/logo.png"></a>
                </li>
                {% endif %}
            </ul> 
        </nav>
        </div>
           
        <div>
        {% block body_block %}
        {% endblock %}
        </div>
    </body>
</html> 

templates/uni_fit/favourites.html
{% extends 'uni_fit/base.html' %}
{% load staticfiles %}
{% block title_block %}
    Favourites
{% endblock %}

{% block body_block %}
<meta name="viewport" content="width=device-width, initial-scale=1">

<div class="category-banner">
    {% if fav_list %}
    <h1 style="width:800px; margin:0 auto; text-align: center;">{{user.username}} your favourites are: </h1>
    <div>
        {% for university in fav_list %}  
            <div class="card">
                <p>
                    <p><strong>{{university.UniName}}</strong></p>
                    <br>{{university.About}}
                    <br><a href={{university.Link}}>Link to University</a>
                    <br><a href="{% url 'uni_fit:favourite_add' university.UniId %}" class="btn btn-outline-primary">Remove</a>
                </p>
            </div>
    </div>
    {% endfor %}
    {% else %}
        <h1 style="width:800px; margin:0 auto; text-align: center;">Please add your favourite universities</h1>
    {% endif %}
</div>

<!-- CSS-->
<link rel="stylesheet" type="text/css" href="{% static 'css/favourites.css' %} " style = "color: rgba(255,255,255,255); opacity: 1;"/>


{% endblock %}

templates/uni_fit/home.html
{% extends 'uni_fit/base.html' %}

{% block title_block %}
    Home
{% endblock %}

{% block body_block %}
<div id="category-banner" class="text-center">
    <div class="container-fluid">
        <h1 class="heading">Welcome to UniFit</h1>

    

<form action="{% url 'uni_fit:home' %}" method="GET" id="form_cdd" >
  
            <select id="countrydropdown" name="countrydropdown" onchange="this.form.submit()">
                <option selected disabled value="null">Select a Country</option>
                <option value="all">All Countries</option>
                {% for c in countrylist %}
                <option >{{ c }}</option>
                {% endfor %}
            </select>       
    
    <div class="text-center">
            <select id="departmentdropdown" name="departmentdropdown" onchange="this.form.submit()">
                <option selected disabled value="null">Select a Department</option>
                <option value="all">All Departments</option>
                {% for c in departmentlist %}
                <option>{{ c }}</option>
                {% endfor %}
            </select>
    </div>
</div>
</form>
<div class="center" style="margin: auto; background: rgba(3,26,92,0.75);  border-radius: 20px;" >
    <table id="unitable" style = "background: transparent">
        <tr>
            <th class="rank">University Rank</th>
            <th>University</th>
        </tr>
        {% for university in universities %}
            <tr>
                <td class="rank" style = "color:rgba(255,255,255,1); opacity: 1;">{{university.UniRank}}</td>
                <td><a href="{% url 'uni_fit:university' university.UniId %}" style = "color:rgba(255,255,255,1)">{{university.UniName }}</a></td>
                <td><a class="custom-checkbox" href="{% url 'uni_fit:favourite_add' university.UniId %}"style = "color: rgba(255,255,255,1)">
                    <i class="glyphicon glyphicon-star-empty"></i>
                    <i class="glyphicon glyphicon-star"></i></a></td>
            </tr>   
        {% endfor %}
    </table>




    
</div>  

<div class="container-fluid">
    <h1 class="heading"></h1>




<!--CSS & JS-->
{% load static %}
<link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css" rel="stylesheet">
<link rel="stylesheet" type="text/css" href="{% static 'css/home.css' %} " style = "color: rgba(255,255,255,255); opacity: 1;"/>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" style = "color: rgba(255,255,255,255); opacity: 1;">
{% load static %}
<script src="{% static 'unifit\static\js\home.js' %}" style = "color: rgba(255,255,255,1)"></script>
{% endblock %}

</div>

templates/uni_fit/index.html
{% extends 'uni_fit/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Index
{% endblock %}

   
{% block body_block %}
<!--CSS-->
<link rel="stylesheet" href="{% static 'css/index.css' %}">

<body>
    <!--CAROUSEL FROM BOOTSTRAP-->
    <div id="carouselExampleCaptions" class="carousel slide" data-bs-ride="carousel">
        <div class="carousel-indicators">
        <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
        <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="1" aria-label="Slide 2"></button>
        <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="2" aria-label="Slide 3"></button>
        </div>

        <div class="carousel-inner">
        <div class="carousel-item active">
            <img src="/static/images/background3.jpg" class="d-block w-100" alt="...">
            <div class="carousel-caption d-none d-md-block">
            <h5>Welcome to UniFit</h5>
            <p>this is the welcome page that the user sees when they are <strong>logged out</strong>
            <div class="slider-btn">
                <a href="{% url 'registration_register' %}"><button class="btn">Sign Up</button></a>
                <a href="{% url 'auth_login' %}"><button class="btn">Login</button></a>
            </div>
            </div>
        </div>

        <div class="carousel-item">
            <img src="/static/images/background6.jpg" class="d-block w-100" alt="...">
            <div class="carousel-caption d-none d-md-block">
            <h5>University Guide</h5>
            <p>this is the welcome page that the user sees when they are <strong>logged out</strong>

            <div class="slider-btn">
                <a href="{% url 'registration_register' %}"><button class="btn">Sign Up</button></a>
                <a href="{% url 'auth_login' %}"><button class="btn">Login</button></a>
            </div>
            </div>
        </div>

        <div class="carousel-item">
            <img src="/static/images/background9.jpg" class="d-block w-100" alt="...">
            <div class="carousel-caption d-none d-md-block">
            <h5>Find your best fit</h5>
            <p>this is the welcome page that the user sees when they are <strong>logged out</strong>

            <div class="slider-btn">
                <a href="{% url 'registration_register' %}"><button class="btn">Sign Up</button></a>
                <a href="{% url 'auth_login' %}"><button class="btn">Login</button></a>
            </div>
            </div>
        </div>
        </div>

        <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
        </button>

        <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
        </button>
    </div>

    <!--JS-->
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>

</body>

{% endblock %}

templates/uni_fit/profile.html
{% extends 'uni_fit/base.html' %}

{% block title_block %}
    Profile
{% endblock %}

{% block body_block %}

<div id="category-banner" class="text-center">
  <div class="container-fluid">
  
<h3>User name : {{user.username}}</h1>

<form action="{% url 'uni_fit:profile' %}" method="GET" id="form_cdd" onSubmit="loadValue(event)">
<div class="row">
  <div class="col-12 col-xl-8">
      <div class="card card-body bg-white border-light shadow-sm mb-4">
          <h2 class="h5 mb-4">Profile information</h2>
          <div class="row">                            
              <div class="col-md-6 mb-5">              
                  <div class="form-group">
                      <label for="grade">Grade in percentage</label>
                      <input name="grade" class="form-control" id="grade" type="number">                  
                  </div>
              </div>
            </dev>                           
            <div class="center" style="margin: auto; background: rgba(3,26,92,0.75);  border-radius: 20px;" >
              <table id="unitable" style = "background: transparent">
                  <tr>
                      <th class="rank  mb-4">University Rank</th>
                      <th class="rank  mb-4">University</th>
                  </tr>
                  {% for university in universities %}
                      <tr>
                          <td class="rank" style = "color:rgba(255,255,255,1); opacity: 1; text-align: center;">{{university.UniRank}}</td>
                          <td><a href="{% url 'uni_fit:university' university.UniId %}" style = "color:rgba(255,255,255,1); text-align: center;">{{university.UniName }}</a></td>                          
                      </tr>   
                  {% endfor %}
              </table>
            </div>
            
      </div>          
    </div>
  </div>

  <div class="col-12 col-xl-4">
    <div class="row">
        <div class="col-12 mb-4">
            <div class="card border-light text-center p-0">
                <div class="profile-cover rounded-top">
                  <img src="/static/images/profile-cover2.png"  class="bg-cover rounded-top"></div>                
                <div class="card-body pb-5">
                    <img src="/static/images/default-profile-picture.png" id="output"
                         class="user-avatar large-avatar rounded-circle mx-auto mt-n7 mb-4">
                    <h4 class="h3">{{ profile.user.username }}</h4>
                    <h4 class="font-weight-normal">{{ profile.user.get_full_name }}</h4>
                    <h5 class="font-weight-normal">
                        {{ request.user.email }}
                    </h5>
                    <p class="text-gray mb-4">{{ profile.address|default:'' }}</p>                    
                </div>
            </div>
        </div>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'auth_password_change' %}">Change Password</a>
        </li>
        <div class="col-12">
            <div class="card card-body bg-white border-light shadow-sm mb-4">
                <h2 class="h5 mb-4">Select profile photo</h2>
                <div class="d-xl-flex align-items-center">
                    <div class="file-field">
                        <div class="d-flex">
                            <div class="d-flex">                                
                                <input name="avatar" type="file" onchange="loadFile(event)">
                                <div class="d-md-block text-left">
                                    <div class="font-weight-normal text-dark mb-1">Choose Image</div>
                                    <div class="text-gray small">JPG, GIF or PNG. Max size of 800K</div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
  </div>
</div>


<!--CSS & JS-->

<script>
var loadFile = function(event) {
	var image = document.getElementById('output');
	image.src = URL.createObjectURL(event.target.files[0]);  
};
</script> 

{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'css/profile.css' %}" />

{% endblock %}

templates/uni_fit/university.html
{% extends 'uni_fit/base.html' %}
{% load staticfiles %}

{% block title_block %}
University Name
{% endblock %}

<meta name="viewport" content="width=device-width, initial-scale=auto;"
{% block body_block %}

<!-- CSS -->

<link rel="stylesheet" href="{% static 'css/university.css' %}">
<div id="category-banner" class="text-center" style = "background-color: rgba(248,249,250,255);">
    <div class="container-fluid">
        <h1>{{ unidata.UniName }}</h1>
   
       

<div style="background-image: url('/static/images/university-backgrounds/{{ unidata.UniId }}.jpg'); background-repeat: no-repeat;  background-position: center; background-size: cover; height:900px;">

    <div class="uni-info column1" style="color: rgba(255,255,255,1); background: rgba(3,26,92,1);">
        <!-- REPLACE THIS WITH POPULATION SCRIPT 'ABOUT' INFO -->
        <h4>About</h4>
        {{unidata.About}}
        <img src = '/static/images/university-backgrounds/{{ unidata.UniId }}.jpg' width="300   " height="337"alt="Image Load Error" style = "max-width:337; max-height:337; object-fit:contain; ">
    </div>

    <div class="review-section column3">
        <h3 class="review-heading">{{ comments.count }} Reviews </h3>
        <div class="container">
            <div class="row">
                <div class="col-md-8 card mb-4  mt-3 ">
                    <div class="card-body">
                        <!-- reviews -->
                        {% for comment in comments %}
                        <div class="comments" style="padding: 10px;">
                            <p class="font-weight-bold">
                                {{ comment.title }}
                                <span class=" text-muted font-weight-normal">
                                    {{ comment.created_on }}
                                </span>
                            </p>
                            {{ comment.comment | linebreaks }}
                        </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="reddit">
        {% if result_list %}
        <h3><i class="fab fa-reddit-square fa-2xl"></i>Popular Reddit Posts</h3>
        
        {% for result in result_list %}
        <div>
            <ul class="post">
                <!--<strong>SUBREDDIT: </strong> {{ result.subreddit }}-->
                <li>
                
                <a href="{{ result.url }}" target=”_blank”><strong>{{ result.title }} </strong></a>
               
                </li>

            </ul>
        </div>
        {% endfor %}
        {% endif %}
    
    </div>

   
</div>
<div class="col-md-8 card mb-4  mt-3" style="background: rgba(3,26,92,1);  border-radius: 20px;">
    <div class="card-body">
        <h3>Leave a Review</h3>
        {% load crispy_forms_tags %}
        <form method="post" style="margin-top: 1.3em;">
            {{ comment_form | crispy }}
            {% csrf_token %}
            <button type="submit" class="btn btn-primary  btn-lg">Submit Review</button>
        </form>
    </div>
</div>

{% endblock %}